### ISSUE TITLE
Getting an error when adding mail account.

### ISSUE THREAD

**Issue by martimarkov** [fusiondirectory/fusiondirectory#10]
I have tested it on my server and on the demo server.

When I try to add an account I get:

`The field 'Primary address' contains invalid characters!`

I use only text in the field.

**Comment by bilbo-the-hobbit** [comment]
hello,

can you tell what you have put in the field, the error message mean you put an invalide caracter for a mail adress

**Comment by martimarkov** [comment]
I just figured it out a moment ago. I was putting just asd instead of asd@domain.com

Silly me. :D

**Comment by bilbo-the-hobbit** [comment]
ok no problem closing it
