### ISSUE TITLE
PHP 7 support?

### ISSUE THREAD

**Issue by nacc** [fusiondirectory/fusiondirectory#12]
Is there any plan for PHP7.0 to be formally supported in the PHP code? I am working on migrating Ubuntu 16.04 to a PHP7.0 only base, and fusiondirectory will be pretty heavily patched to support PHP7.0. I can contribute those patches back to this project, if that would be acceptable (although I am not sure how best, for instance, to support both mod_php and mod_php5 in the apache configuration, multiple if-statements?)

**Comment by MCMic** [comment]
Hello,
Yes we intend to support PHP7 at some point but had little time to look into that for now.
We have already 2 opened tickets related to PHP7:
https://forge.fusiondirectory.org/issues/4570
https://forge.fusiondirectory.org/issues/4571

I’ve looked quickly into the second one and did not understood what could go wrong.

You are more than welcome to submit patches for PHP7 support as long as they don’t break support of older PHP versions.

**Comment by bilbo-the-hobbit** [comment]
hello,

as said we will be full php 7.0 compliant at some point, we welcome all the ubuntu patches you can send us for inclusion, you can do PR right here

Cheers

**Comment by bilbo-the-hobbit** [comment]
Hello,

we started cleaning the code to make it php5 and php7 compatible, you can see the progress here
http://demo-fixes.fusiondirectory.org who is running the latest php7 code in php5, we will open a full php7 demo boxe soon

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

we have fixed most of the php7 visible bugs, support for PHP7 will be inside FusionDirectory 1.0.13, this version will be uploaded to debian.

I'm closing this bug now

**Comment by nacc** [comment]
@bilbo-the-hobbit Thanks for the update! I don't think that version has been uploaded to Debian yet, and seems like fusiondirectory in 16.04 is probably busted. Any ETA on that upload happening?

**Comment by bilbo-the-hobbit** [comment]
Hello,

yes more fixes where needed after getting 1.0.13 out, 1.0.14 will be the debian version

Cheers

**Comment by bilbo-the-hobbit** [comment]
Hello,

Closing this as it will be 1.0.15 to go to Debian After all :)

Cheers
