### ISSUE TITLE
locale/pt_BR/fusiondirectory.po incorrectly refers to php5-omagick

### ISSUE THREAD

**Issue by nacc** [fusiondirectory/fusiondirectory#13]
I think this is a typo?

**Comment by bilbo-the-hobbit** [comment]
surely :) 

we are using transifex to translate FusionDirectory. If you wan to help just register and Join the team of the language you want to translate https://www.transifex.com/fusiondirectory/

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

fixed in transifex, will be in next release

Cheers
