### ISSUE TITLE
Dependences of packages

### ISSUE THREAD

**Issue by shizacat** [fusiondirectory/fusiondirectory#15]
Hello,
Thanks you for this project!

I think it would be nice, if he(fusiondirectory package) not pulled as much dependences of packages. From this is very many problems in  deployment and settup.

May be you look on - composer - manager package for php.

Packages that, I think not need: javascript-common, prototype.js, scriptaculous, smarty3, smarty-gettext, fusiondirectory-smarty3-acl-render. Is the same - javascript-common - not obvious "location" in apache - what if apache backend, ngin frontend with virtualhost, or docker container.

You did not think to add docker image.

**Comment by bilbo-the-hobbit** [comment]
hello,

i don't understand the question, packaging is a whole corresponding to the distribution you are installing into.

if you want that liberty installing from source would be the way but i don't recommend it.

Could you give us more information about what you are trying to achieve, as most of the mentioned component are necessary to make it run correctly

We will never use composer as source is not the main distribution of the project but the packaging is 

Cheers

**Comment by shizacat** [comment]
My goal make docker container.
OS: ubuntu (deb packages).
I will try to explain the parts of my thought

Look on packages: javascript-common
debian-fusiondirectory/debian/patches/2002_fusiondirectory-headers.patch
```
 ~...
 -  <script src="include/controls.js" type="text/javascript"></script>
 +  <script src="javascript/scriptaculous/scriptaculous.js" type="text/javascript"></script>
 ~...
```
i.e javascript files is component - javascript-common
- remove this patch
- then, themselves files: scriptaculous.js, builder.js, effects.js, dragdrop.js, controls.js, prototype.js
put into "include" folder
- and remove dependens prom package (fusuondirectory): debian-fusiondirectory/debian/control

Yes, it manual check version, but i think, that so more pros

**Comment by bilbo-the-hobbit** [comment]
hello,

what you ask cannot be done, because packages need those patches and dependencies to work correctly. Other peoples already does docker images and never asked to changes anything in the packages.

Cheers
