### ISSUE TITLE
Wizard Step "Setup_LDAP" - field "base"

### ISSUE THREAD

**Issue by shizacat** [fusiondirectory/fusiondirectory#20]
Hello,
Do you tried to setup fusindirectory 1.0.12? Into tab "Setup LDAP", field "base" is SelectAttribute - may be he need be String - else how edit "base"?

**Comment by bilbo-the-hobbit** [comment]
hello,

the base is automatically detected from your ldap server.

Cheers

**Comment by shizacat** [comment]
hmmm
Connection URI is IP address
When i click "retry" - show messages "The required field 'Base' is empty!"

Only when i edited code the manual - set this field into String and filled his
Then it began to work

**Comment by bilbo-the-hobbit** [comment]
hello,

it works correctly but as i said you ldap tree should allow this in the acl 

olcAccess: {1}to dn.exact="" by * read
olcAccess: {2}to dn.base="cn=Subschema" by * read

its normally by default on Debian

Cheers

**Comment by jmcd79** [comment]
Hi,
In this moment i have the same issue, can help me to solve this?
is needed make anything before the wizard setup?

**Comment by bilbo-the-hobbit** [comment]
hello,

the answer is above you need certain acl in your ldap tree.

on which distro are you ?

Cheers

**Comment by jmcd79** [comment]
in this moment i have a new installation centos 7 a make the steps mentioned on :+1: https://documentation.fusiondirectory.org/en/documentation/admin_installation_centos_7

**Comment by bilbo-the-hobbit** [comment]
hello,

just checked you need to add the  two acl mentionned above into the frontend db in your cn=config backend

Cheers

**Comment by jmcd79** [comment]
sorry for my ignorance
but will that I can explain where I make this change

Thks

**Comment by bilbo-the-hobbit** [comment]
hello,

you need to create an ldif example attached and put it inside you ldap server with an ldapadd 

dn: olcDatabase={-1}frontend,cn=config
changetype: modify
add: olcAccess
olcAccess: {0}to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage by * break
olcAccess: {1}to dn.exact="" by * read
olcAccess: {2}to dn.base="cn=Subschema" by * read

**Comment by bilbo-the-hobbit** [comment]
hello,

but to be clear we didnt get this probleme on our test under centos 6 and Centos 7. Which version of centos 7 are you using 

Cheers

**Comment by jmcd79** [comment]
Hi,     
        Chassis: vm
         Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.18.2.el7.x86_64
      Architecture: x86-64

I try to connect  AD  on windows server 2012


Thks

**Comment by bilbo-the-hobbit** [comment]
hello,

i mean the minor version of Centos 7.X. And what does I try to connect AD on windows server 2012 mean ? You try to use FusionDirectory on AD ?

Cheers

**Comment by jmcd79** [comment]
Hi,
ldd (GNU libc) 2.17
Installed Packages
glibc.x86_64	2.17-106.el7_2.6    

Yes im try connect fusiondirectory to my AD

**Comment by bilbo-the-hobbit** [comment]
hello,

this will not work as AD is not extensible and we cannot use AD schema. The best way to do it is to have openldap and AD and synchronize between the two

Cheers

**Comment by jmcd79** [comment]
Ok :)
Thks for your time and help.
I will try with openldap

**Comment by gavit** [comment]
I also have the same issue on CentOS Linux release 7.2.1511 (Core)
I'll try to add the lines above.
`
olcAccess: {1}to dn.exact="" by * read
olcAccess: {2}to dn.base="cn=Subschema" by * read
`
I also don't like the fact that it installed the directory in /usr/share/fusiondirectory/html instead of in /var/www/html/fusiondirectory
I had to manually symlink:
`ln -s /etc/fusiondirectory/fusiondirectory-apache.conf /etc/httpd/sites-enabled/`

Well actually I changed the content:
`
# Include FusionDirectory to your web service
<VirtualHost *:80>
  ServerName fusiondirectory.example.sr
  Redirect permanent / https://fusiondirectory.example.sr/
</VirtualHost>

<VirtualHost *:443>
    ServerName fusiondirectory.example.sr
    ServerAdmin system.administrators@example.sr
    DocumentRoot /usr/share/fusiondirectory/html
    SSLEngine on
    SSLCertificateFile "/etc/ssl/certs/wildcard_example_sr.pem"
    SSLCertificateChainFile "/etc/ssl/certs/wildcard_example_sr.pem"
    SSLCertificateKeyFile "/etc/ssl/certs/wildcard_example_sr.pem"
    ErrorLog /var/log/httpd/sr.example.fusiondirectory.error.log
    CustomLog /var/log/httpd/sr.example.fusiondirectory.access.log combined
    <Directory />
      Options FollowSymLinks
      AllowOverride None
    </Directory>
    <Directory /usr/share/fusiondirectory/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Require all granted
        php_admin_flag engine on
        php_admin_flag register_globals off
        php_admin_flag allow_call_time_pass_reference off
        php_admin_flag expose_php off
        php_admin_flag zend.ze1_compatibility_mode off
        php_admin_flag register_long_arrays off
        php_admin_value upload_tmp_dir /var/spool/fusiondirectory/
        php_admin_value session.cookie_lifetime 0
    # Remove the comment from the line below if you use fusiondirectory-setup --encrypt-passwords
    #   include /etc/fusiondirectory/fusiondirectory.secrets
    </Directory>
</VirtualHost>
`

**Comment by bilbo-the-hobbit** [comment]
Hello,

yes the {1}frontend database is broken in basic install form openldap on centos, just remove the file and restart openldap it will recreate a good one

For apache please dont add stuff in a issues that no linked to the title and subject

Cheers
