### ISSUE TITLE
Users plugin : FUNCTIONAL filter not working as expected (fix)

### ISSUE THREAD

**Issue by luminouw** [fusiondirectory/fusiondirectory#25]
Hi there,

after installing and setting up everything following the doc (last debian:jessie version), I'm able to create users but if I don't add any posix or mail attribute, they aren't listed in the Users page and the only way to confirm they exist is if I create a group and try to add members, there I can find them.

I tried to force the FUNCTIONAL filter in user-filter.xml, it didn't work, so I took a look at class_userManagement.inc.

With some ldapsearch queries I figured out that the filter built on line 99 with
`$this->filter->elements['FUNCTIONAL']['set']  = '(!(|(objectClass='.implode(')(objectClass=', $classes).')))';`
was building something like
`(!(|(objectClass=posixAccount)(objectClass=gosaMailAccount)))`
which returns zero result (users list stays empty, ldapsearch returns 0 result).

I fixed this here with
`$this->filter->elements['FUNCTIONAL']['set'] = '(|(!(objectClass='.implode('))(!(objectClass=', $classes).')))';`
which builds the following filter
`(|(!(objectClass=posixAccount))(!(objectClass=gosaMailAccount)))`
setting the NOT condition on every member of the OR fixes the way I think it should filter people without any of the posixAccount or gosaMailAccount classes.

With this filter, I'm now able to list my users.

Thank you

**Comment by bilbo-the-hobbit** [comment]
hello,

does this report goes with your fix in #26 ?

Cheers

**Comment by luminouw** [comment]
Hello,

yes the PR is related to this report.

**Comment by luminouw** [comment]
Hi there,

bad configuration on my side, the mail plugin was installed in FusionDirectory but the schema associated to the plugin hasn't been loaded in the LDAP instance, once the schema inserted everything works like it's supposed to. Sorry for the mistake : )
