### ISSUE TITLE
A few updates ago I started getting fdHttpAuthActivated error

### ISSUE THREAD

**Issue by martimarkov** [fusiondirectory/fusiondirectory#29]
I'm getting: 

`LDAP operation failed!

Object: cn=config,ou=fusiondirectory,dc=domain,dc=com

Error: Undefined attribute type - attribute: fdHttpAuthActivated (fdHttpAuthActivated: attribute type undefined, while operating on 'cn=config,ou=fusiondirectory,dc= domain,dc=com' using LDAP server 'ldap://localhost:389')`

This error comes up when I login.

**Comment by bilbo-the-hobbit** [comment]
hello,

did you follow the updates notice to go from one version to another ?

https://documentation.fusiondirectory.org/en/documentation_admin

it seems your core-fd-conf.schema is not uptodate

Cheers

**Comment by martimarkov** [comment]
... Seems to be working... :D I feel silly. :D
