### ISSUE TITLE
Incorporating boostrapt script for this organisation.

### ISSUE THREAD

**Issue by mikefaille** [fusiondirectory/fusiondirectory#30]
Referring to this discussion : https://github.com/fusiondirectory/fusiondirectory/issues/14#issuecomment-235323682

I built Docker images for Fusion Directory and I'm ready to share my project.

To quick start faster, I suggest creating a repositories dedicated for bootstrapping. It could be named : fusiondirectory/fusiondirectory-bootstrap

Since I don’t use source code but package, my Dockerfiles isn't the best to be included in the main repository.

Eventually, this repository could hold many ways to bootstrap Fusion Directory. Then checkouting fusiondirectory/fusiondirectory-boostrap without main code could help to boostrap faster. Maybe, fusiondirectory/fusiondirectory project could have a link to fusiondirectory/fusiondirectory-bootstrap.

Cheers,
Michael

cc : @bilbo-the-hobbit

**Comment by bilbo-the-hobbit** [comment]
Hello mike,

yes i need to think about how to include that in our git repos and process, ou main repos are at git.fusiondirectory.org and github is only a mirror.

i will think about this and let you know rapidly

Cheers

**Comment by mikefaille** [comment]
@bilbo-the-hobbit Have you some news about it ?

**Comment by bilbo-the-hobbit** [comment]
hello,

yes i have delays :) we juste get out a new version of fusiondirectory. will look a it during this week

Cheers

**Comment by bilbo-the-hobbit** [comment]
I must apologize for the delays, now that the stable huge 1.1 version is about to get out, we will be able to resume soon

**Comment by mikefaille** [comment]
Ok cool. I'll check the next week to be sure everything is ok in my work.

**Comment by bilbo-the-hobbit** [comment]
hello,

we migrated to gitlab and started using docker there, will come back to you when we have a clear picture of what we want.

Cheers
