### ISSUE TITLE
fusiondirectory-plugin-fusioninventory

### ISSUE THREAD

**Issue by GreenItSolutions** [fusiondirectory/fusiondirectory#35]
Hi,
I search to integrate xml inventory files generated with fusioninventory to fusiondirectory.
Is there any documentation to do this ?

We have allready find how to populate fusiondirectory inventory objects directly from fusioninventory-agent command. But we want to generate first with fusioninventory-agent an xml file on each computer and "inject" this files in fusiondirectory inventory objects.

The maintener of fusioninventory-agent says he can't help us and invite us to write to you.

Thanks in advance,

**Comment by bilbo-the-hobbit** [comment]
Hello,

we don't support using the xml files only the direct connexion between fusioninventory-agent and fusiondirectory.

we will accept a code contribution to do that 

Cheers
