### ISSUE TITLE
Strange dn issue when adding a group or deleting a group

### ISSUE THREAD

**Issue by worldcitizen** [fusiondirectory/fusiondirectory#38]
When I add and I safe the user data the dn of the user changes from dn: uid= to dn: cn=givenname Sirname+uid=uid,ou=people,dc=*dc*,dc=com visa versa.

This only happens on one system.
This is a Debian Jessie server with the 1.0.16 and newer packages created by fusiondirectory installed.

I've attached the config part of ldap, i have anonymized some parts.
The only difference that I notice is that the group name is group in stead of the standard groups name.

fdOGroupRDN: ou=groups
fdGroupRDN: ou=group

I've changed both to group, this didn't solve the issue.

In previous fusiondirectory versions the option "'Include personal title in user DN" existed, but this option is gone.

I've attached the config part of LDAP.

[config.txt](https://github.com/fusiondirectory/fusiondirectory/files/909695/config.txt)

I see this issue in my fusiondirectory 10.0.16 and up. It looks like a ldap item issue. If I connect the instance to another ldap instance I don't see this issue.

This issue was also reported at: https://forge.fusiondirectory.org/issues/5238

**Comment by MCMic** [comment]
Answered on the redmine

**Comment by worldcitizen** [comment]
I'm sorry to contact you via github.
But I'm not able to log into redmine any more: Your account is locked. I've reset my password but this didn't unlock my account. I can log into fusiondirectory.
I don't see an option to contact an admin via Redmine.

**Comment by MCMic** [comment]
Should be unlocked now.
