### ISSUE TITLE
Debian Jessie repository key expired

### ISSUE THREAD

**Issue by the-nic** [fusiondirectory/fusiondirectory#39]
Its not directly related to the code, but the repository key for debian Jessie packages has expired, therefore signatures will be checked anymore.

**Comment by bilbo-the-hobbit** [comment]
hello,

it already has been corrected yesterday, the key expiration has been postponed. You can execute the command here :

[Getting the official GPG keys to active package signature](https://documentation.fusiondirectory.org/en/documentation/admin_get_ggp_keys)

to update the key

a new key will be created with stronger crypto for the 1.1 release

Cheers
