### ISSUE TITLE
Change user password ACL

### ISSUE THREAD

**Issue by Samgarr** [fusiondirectory/fusiondirectory#40]
Hi,
it is possible to allow user change their password without possibility change password hash algorithm? Thanks!

**Comment by bilbo-the-hobbit** [comment]
Yes it is yon can lock the password method in the configuration and enforce the use of only this method

Read the documentation at documentation.fusiondirectory.org

**Comment by bilbo-the-hobbit** [comment]
hello,

i'am closing this since no action till 300 days
