### ISSUE TITLE
SASL missing from Password default hash field in setup

### ISSUE THREAD

**Issue by DBLouis** [fusiondirectory/fusiondirectory#42]
Why can't I choose SASL method ? Is it not enabled by default ?
In include/password-methods/ there is a file for sasl as well as md5, sha... but it does not show up in the drop down menu.

**Comment by bilbo-the-hobbit** [comment]
Hello,

closing it as the bug https://forge.fusiondirectory.org/issues/5589 has been opened on the forge

Cheers
