### ISSUE TITLE
Password with limited length

### ISSUE THREAD

**Issue by zeronounours** [fusiondirectory/fusiondirectory#45]
The length of the of the password is limited in the smarty template. I see no technical reasons for this. If so, it really should be deleted because it's a non-sense to limit it.

In `ihtml/themes/breezy/login.tpl`, currently line 37:
```html
 <input type="password" name="password" id="password" maxlength="40" value="" title="{t}Password{/t}"/>
```

**Comment by MCMic** [comment]
See https://forge.fusiondirectory.org/issues/5668

**Comment by bilbo-the-hobbit** [comment]
hello,

since we migrated to gitlab the url is https://gitlab.fusiondirectory.org/fusiondirectory/fd/issues/5668

Cheers
