### ISSUE TITLE
FDPRIMARYGROUPFILTER attribute is stuck on users

### ISSUE THREAD

**Issue by martimarkov** [fusiondirectory/fusiondirectory#46]
I'm trying to create a sync between two instances of OpenLDAP.

I was getting this error message:

`syncrepl_message_to_entry: rid=001 mods check (FDPRIMARYGROUPFILTER: attribute type undefined)`

I started investigating and found that it was a deprecated attribute that I have removed... But! When I grep in /var/lib/ldap/data.mdb I get a few matches. 

Also when I use JXplorer to search for * FDPRIMARYGROUPFILTER* I only get a list of users (the only objects containing references to this dead attribute).

Any pointers on how to fix this?

**Comment by martimarkov** [comment]
@bilbo-the-hobbit Any ideas, this is blocking my ability to any syncs?

**Comment by bilbo-the-hobbit** [comment]
hello,

the error you are seeing is on the slave ? are all the schema in sync master and slave ?

you grep is on the master or the slave ?

**Comment by martimarkov** [comment]
The error is seen on the slave. I'm not 100% sure how to check that. :/

The grep was performed on the master.


The slave was created recently when the need for a second server was felt. There is no data in it but I have installed fusion directory on it as well and imported all the schemas that were imported on the first one. (I should probably check if there is anything missing but I'm not 100% sure how).


The first server's fusion directory was installed ages ago and upgrade thought multiple versions.

**Comment by bilbo-the-hobbit** [comment]
Hello,

seems a migration issue, please feel free to discuss this on the mailing list

https://www.fusiondirectory.org/contact-us/

Cheers
