### ISSUE TITLE
Re-Scaling of User's jpegPhoto

### ISSUE THREAD

**Issue by gohrner** [fusiondirectory/fusiondirectory#48]
(I'm opening this issue on "plugin" as I don't seem to be able to open it for the core component.)

I'm using FusionDirectory 1.3 from the project repository. If I upload a profile photo for a user, it seems to get re-scaled to 150x150 pixels which looks really ugly in software that then tries to display this image at a larger size.

I also could not find any way to re-configure the desired target size. Did I miss the configuration option to adjust this somewhere?

The LDAP spec does not seem to imposte a specific limit on the image size. Obviously I do not want to upload 20 megapixle portrait photographs to my LDAP server, but if it's not possible to configure the target size to the size actually expected / needed by software used in an organization, I'd consider this to be a bug or at least a missing feature.

**Comment by bilbo-the-hobbit** [comment]
hello @gohrner,

there is no configuration settings to manage that, we should discuss this @MCMic what do you think about adding such an option, are there drawback ?

Cheers

**Comment by MCMic** [comment]
@bilbo-the-hobbit No I guess this could be a configurable option. I never encountered software rendering those at large sizes before.

**Comment by bilbo-the-hobbit** [comment]
@gohrner @MCMic,

yes i think we can put a configurable option, but keeping it sensible to avoid putting huge picture in there. telling user that they cannot for example put a 500x500 picture or something like that

Cheers

**Comment by MCMic** [comment]
@gohrner Should be fixed in 1.4-dev by https://gitlab.fusiondirectory.org/fusiondirectory/fd/issues/6049

**Comment by bilbo-the-hobbit** [comment]
hello @gohrner,

will be in 1.4 final

Closing this bug

Cheers
