### ISSUE TITLE
Password crypt rounds support

### ISSUE THREAD

**Issue by MichalMMac** [fusiondirectory/fusiondirectory#49]
Hello.

Would it be possible for Fusion Directory to support setting number of rounds (iterations) in password CRYPT format using SHA-512?

https://en.wikipedia.org/wiki/Crypt_(C)

**Comment by bilbo-the-hobbit** [comment]
hello @MichalMMac,

do you have any pratical implementation for this in php or another language we can look at

Cheers

**Comment by MichalMMac** [comment]
I am no php programmer but...

[Here](https://github.com/fusiondirectory/fusiondirectory/blob/db0feb2f05863ae3013b638e127ef6c54bd27b57/include/password-methods/class_password-methods-crypt.inc) we are preparing salt for the `crypt()` function.
```
    if ($this->hash == "crypt/sha-512") {
      $salt = "\$6\$";
      for ($i = 0; $i < 16; $i++) {
          $salt .= get_random_char();
      }
      $salt .= "\$";
    }
```
After that we pass password and the generated salt to `crypt()` function.

```
return "{CRYPT}".crypt($pwd, $salt);
```

Acording to the `crypt()` [documentation](https://www.php.net/manual/en/function.crypt.php) there are only two parameters. One for password and the second one for the salt.

**Example #3 Using crypt() with different hash types** shows:

```
if (CRYPT_SHA512 == 1) {
    echo 'SHA-512:      ' . crypt('rasmuslerdorf', '$6$rounds=5000$usesomesillystringforsalt$') . "\n";
}
?>
```

`$6$rounds=5000$usesomesillystringforsalt$` is the salt paramater with rounds set to 5000 (which is the same as default).

For SHA-512 docs say:

> CRYPT_SHA512 - SHA-512 hash with a sixteen character salt prefixed with $6$. If the salt string starts with 'rounds=<N>$', the numeric value of N is used to indicate how many times the hashing loop should be executed, much like the cost parameter on Blowfish. The default number of rounds is 5000, there is a minimum of 1000 and a maximum of 999,999,999. Any selection of N outside this range will be truncated to the nearest limit.

FusionDirectory configured to store passwords in LDAP as `crypt/sha-512` stores this hash in the LDAP: `{CRYPT}$6$pvDAyShQrNq7j1gG$QOO6SAY5L9NkVZY0wjNcUnKQACI5OkiENbsLMx6vi6G/.....`

- Hash type is specified: `$6` -> SHA-512.
- `$pvDAyShQrNq7j1gG$` is 16 char longh salt.
- Number of rounds is not specified -> 5000 default should be used.

It would be nice to have an option to specify number of rounds for the `Password default hash` requirment.

**Comment by bilbo-the-hobbit** [comment]
hello @MichalMMac,

thanks for the explanation

@MCMic what do you think of this ?

Cheesr

**Comment by MCMic** [comment]
@bilbo-the-hobbit We may add a configuration option for this but it should be global, not for each user.
It would add one more option to the configuration screen, that most people will not use, so I’m not sure how useful this is.

**Comment by bilbo-the-hobbit** [comment]
> @bilbo-the-hobbit We may add a configuration option for this but it should be global, not for each user.
> It would add one more option to the configuration screen, that most people will not use, so I’m not sure how useful this is.

yes it should be global and could be used in more security minded setup. 

What would be the cost in time and risk to add this functionality

Cheers
