### ISSUE TITLE
Group editing

### ISSUE THREAD

**Issue by lgaggini** [fusiondirectory/fusiondirectory#5]
Hi,

base version 1.0.74 with samba plugin, installed from wheezy repo on Ubuntu Server 14.04, if I try to edit an existent group and then I try to save by Ok or Apply button I receive the following error and the group isn't updated:

"There is already an entry with this 'Name' attribute in the system!"

Keep on the good work.

**Comment by bilbo-the-hobbit** [comment]
hello,

did you still encounter this issues on recent FusionDirectory release ?

Cheers

**Comment by lgaggini** [comment]
Hi Bilbo,
I can't access that installation anymore because I change company / job and I don't have any other Fusion directory installation in place at the moment.
I'm sorry.

**Comment by bilbo-the-hobbit** [comment]
hello,
okay as we don't have any report on 1.0.9.x for this, i will close the report

Cheers
