### ISSUE TITLE
Date macros doesn't work on user unix password expiration date

### ISSUE THREAD

**Issue by jadjay** [fusiondirectory/fusiondirectory#50]
Version : FusionDirectory, 1.3
Type of object : Template of user, with unix user schema

- Set template's unix account password expiration date to : %d[today+1year+3months]|%
- Create a user
- His unix account password expiration date is set to : 28 january 1970

I have tested the DATE STRING with date command line.

If you have questions, 

Regards,

**Comment by MCMic** [comment]
See https://gitlab.fusiondirectory.org/fusiondirectory/fd/issues/6007#note_69020

You need to specify epoch as format, so in your case `%d[today+1year+3months,epoch]|%`

**Comment by bilbo-the-hobbit** [comment]
hello @jadjay,

fixed in the official documentation

https://fusiondirectory-user-manual.readthedocs.io/en/1.3/templates/macro.html

Cheers
