### ISSUE TITLE
Password Policy default not working

### ISSUE THREAD

**Issue by jacotec** [fusiondirectory/fusiondirectory#51]
I'm running fusiondirectory with the ppolicies plugin and scheme added. In general it's working, but the default password policy is not applied to the accounts.

The default if configured in /usr/share/doc/fusiondirectory-plugin-ppolicy/ppolicyconfig.ldif as follows:

`olcPPolicyDefault: cn=default,ou=ppolicies,dc=mydomain,dc=de`

I've created a password policy called "default" in FD:
![image](https://user-images.githubusercontent.com/3321655/67478891-3a2e1200-f65d-11e9-8fb1-b4d7c43d349d.png)

Also in FD, this policy is displayed with the path: "cn=default,ou=ppolicies,dc=mydomain,dc=de"

I can check the function of the policy with my frontend (PWM-Project). When I log in as a user and go to "change password", the correct policy is read and displayed as long as the user is definitely assigned to the policy "default":
![image](https://user-images.githubusercontent.com/3321655/67479103-97c25e80-f65d-11e9-890f-7b932e5960a4.png)

This is working so far. The big issue is, that the policy **is not applied on the standard setting of the users "Use default"**:
![image](https://user-images.githubusercontent.com/3321655/67479406-46669f00-f65e-11e9-96ec-433bb6d823e4.png)

With this setting, my default policy "cn=default,ou=ppolicies,dc=mydomain,dc=de" is not applied and in use for the user!

In my understanding this setting should use the default policy!

Also the plugin configuration is showing the right policy:
![image](https://user-images.githubusercontent.com/3321655/67479234-ef60ca00-f65d-11e9-9501-50c188b7c898.png)
... which results in"cn=default,ou=ppolicies,dc=mydomain,dc=de"

Is this a confirmed bug or is there any workaround? I have a project on hold just because the default is not working ...

**Comment by bilbo-the-hobbit** [comment]
hello @jacotec,

we are not aware of any issues around default policy on ppolicy, we will check it, what fusiondirectory version do you use ?

if you need rapid response you can buy professional support https://www.fusiondirectory.org/support/

Cheers

**Comment by jacotec** [comment]
Thank you, @bilbo-the-hobbit 

At least a workaround / patch would be great. I'm using FD 1.3 (the latest version from your distribution repos).

Regarding pro support: It's a private project and for the use of a non-profit-org ... so there are unfortunately no funds.

**Comment by MCMic** [comment]
If you select «Use default», pwdPolicySubentry is left empty, as suggested by zytrax documentation: http://www.zytrax.com/books/ldap/ch6/ppolicy.html#pwdpolicysubentry

Either your ppolicy configuration is wrong (default policy not correctly defined) or the frontend you use do not respect default policy (If it uses an LDAP extended operation to change the password this should not be possible, but if it checks policy «by hand» it may do it wrong).

**Comment by bilbo-the-hobbit** [comment]
@jacotec no news about this since nearly a year, i'am closing this bug

Cheers
