### ISSUE TITLE
Can't contact LDAP server through TLS

### ISSUE THREAD

**Issue by Victor-Morel** [fusiondirectory/fusiondirectory#52]
I followed the [tutorial for TLS support](https://documentation.fusiondirectory.org/en/documentation/tls_support), everything went smoothly, but the last step, ie., testing from a client, returns `ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)`

What step could have gone wrong?
What can I do to identify the issue?

**Comment by bilbo-the-hobbit** [comment]
hello @Victor-Morel,

this doc is obsolete and should not be followed. We will remove the whole doc today as the new FusionDirectory doc is at https://fusiondirectory-user-manual.readthedocs.io/en/1.3/index.html

Cheers

**Comment by Victor-Morel** [comment]
Ok, thanks for the pointer (maybe the old doc should be more visibly tagged as obsolete...)

However, I cannot find any similar tutorial for TLS support in the new doc, under which denomination is it?

**Comment by Victor-Morel** [comment]
?

**Comment by bilbo-the-hobbit** [comment]
hello @Victor-Morel,

we no longer document how to use openldap its not our scope, you should read the openldap documentation

Cheers
