### ISSUE TITLE
Documentation for DNS and DHCP missing 

### ISSUE THREAD

**Issue by liszca** [fusiondirectory/fusiondirectory#54]
Searching for documentation on DNS and DHCP I didn't find any entries, here is where I was looking:
https://fusiondirectory-user-manual.readthedocs.io/en/1.3/plugins

**Comment by bilbo-the-hobbit** [comment]
hello @liszca,

exactly its no written yet :)

you can subscribe to the user mailing list if you have question

https://www.fusiondirectory.org/en/community/

Cheers
