### ISSUE TITLE
Password reset complains about invalid characters

### ISSUE THREAD

**Issue by liszca** [fusiondirectory/fusiondirectory#55]
- Trying to reset an accounts password with its email address I get the following error message:

```
The field 'Contact your administrator, there was a problem with mail server' contains invalid characters! 
```

- Changing the "@" to "%40" for URL Encoding gives me an other error:

```
There is no account using email "mymail%40gmail.com" 
```

Installed plugins:

- ldapdump
- ldapmanager
- mail
- dsa
- personal

Let me know if you need further information about my setup.

**Comment by joergmschulz** [comment]
Here as well. Even with installed system, dns plugins. I didn't find out where that mail server has to be configured???

**Comment by bilbo-the-hobbit** [comment]
hello @joergmschulz and @liszca 

as there are not bug please better subscribe to the user mailing list https://lists.fusiondirectory.org/wws/info/users  to ask those kind of question

Cheers
