### ISSUE TITLE
Problem with setup on centos 7 (inside podman/docker) when follow the official documentation

### ISSUE THREAD

**Issue by conexaoinfraestrutura** [fusiondirectory/fusiondirectory#56]
I follow the site instalation procedure, but i'm stucked in this error.
https://fusiondirectory-user-manual.readthedocs.io/en/1.3/install/centos/centos-fd-install.html#install-fusiondirectory

http://10.88.0.9/fusiondirectory/setup.php

Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:/usr/share/fusiondirectory/setup/setup_welcome.tpl" on line 3 "{t}This seems to be the first time you start FusionDirectory - we didn't find any configuration right now. This simple wizard intends to help you while setting it up.{/t}" unknown tag 't' <-- thrown in /usr/share/php/Smarty/sysplugins/smarty_internal_templatecompilerbase.php on line 3

php-json-7.1.33-5.el7.remi.x86_64
php-pdo-7.1.33-5.el7.remi.x86_64
php-pear-CAS-1.3.8-1.el7.remi.noarch
php-pecl-imagick-3.4.4-9.el7.remi.7.1.x86_64
php-Smarty3-3.1.18-2.el7.centos.noarch
php-common-7.1.33-5.el7.remi.x86_64
php-mbstring-7.1.33-5.el7.remi.x86_64
php-ldap-7.1.33-5.el7.remi.x86_64
php-fedora-autoloader-1.0.1-2.el7.remi.noarch
php-imap-7.1.33-5.el7.remi.x86_64
php-xml-7.1.33-5.el7.remi.x86_64
php-Smarty3-gettext-1.1.0-2.el7.centos.noarch
php-gd-7.1.33-5.el7.remi.x86_64
php-cli-7.1.33-5.el7.remi.x86_64
php-7.1.33-5.el7.remi.x86_64
php-Smarty-3.1.33-1.el7.remi.noarch

CentOS Linux release 7.7.1908 (Core)

**Comment by bilbo-the-hobbit** [comment]
hello @conexaoinfraestrutura,

package are currently being fixed for centos, should be there next week.

For installation issues its better to use the mailing list

https://www.fusiondirectory.org/en/community/

Cheers
