### ISSUE TITLE
PHP Error "Setting locale to fr_FR.UTF-8 failed" in setup

### ISSUE THREAD

**Issue by osfrance** [fusiondirectory/fusiondirectory#57]
Hi,
I try to make a docker container from Fusion-directory in stretch, but when I go to setup.php, IU had this PHP error : 
> Trace[1]: function trigger_error | File: /usr/share/fusiondirectory/include/class_Language.inc (Line 50) | Type: -
> -- | -- | --
> Arguments: "Setting locale to fr_FR.UTF-8 failed"
> Trace[2]: class Language / function init | File: /usr/share/fusiondirectory/html/setup.php (Line 89) | Type: static
> Arguments: "fr_FR.UTF-8"

I think, I don't have French language in my stretch image, what can I do for resolve this issue ?
(PS: If y continue in English, FusionDirectory works well...)
Thanks !!!

**Comment by bilbo-the-hobbit** [comment]
hello @osfrance,

this is a bug tracker, for installation issue please use the mailing list

https://www.fusiondirectory.org/communaute/

Cheers

**Comment by osfrance** [comment]
Hi, with mailiing list I use for submit bug issue ? 
conseil@lists.fusiondirectory.org, 
developpers@lists.fusiondirectory.org, 
packages@lists.fusiondirectory.org
security@lists.fusiondirectory.org,
 users@lists.fusiondirectory.org

**Comment by bilbo-the-hobbit** [comment]
hello @osfrance,

the user list, bu this is not a bug bu a configuration issue :)

**Comment by osfrance** [comment]
Ok thanks I'll post it !
