### ISSUE TITLE
Dependency Package php-Smarty3 missing from Repos

### ISSUE THREAD

**Issue by saileshabburu** [fusiondirectory/fusiondirectory#59]
Fusion directory installations fails for all the versions in RHEL 7 owing to missing dependency php-Smarty3 from fusiondirectory-extra repos

**Comment by bilbo-the-hobbit** [comment]
hello @saileshabburu 

normally this has been corrected see 

https://fusiondirectory-user-manual.readthedocs.io/en/1.3/repositories/centos.html#centos-7-rhel-7

Cheers
