### ISSUE TITLE
an error occurred while I install fusiondirectory into my LDAP server

### ISSUE THREAD

**Issue by stuart3501** [fusiondirectory/fusiondirectory#6]
I try to install fusiondirectory into my openldap server
But when I try to setup it in the web page, it shows an error message: 
"Bind as user 'admin,dc=ldap,dc=acer,dc=com' failed! "
But while I try to use this command: "telnet localhost 389"
It can respond quickly.
Does anyone can give me an idea?
Thanks for your help
https://drive.google.com/file/d/0B1w_R1KFe0MdMGNSNU5pdWpnU3M/edit?usp=sharing

**Comment by RushOnline** [comment]
Try to set **Admin DN** field to _**cn=admin**_
