### ISSUE TITLE
E: Unable to locate package fusiondirectory-plugin-zimbra, 

### ISSUE THREAD

**Issue by s33k3rs** [fusiondirectory/fusiondirectory#61]
I have installed the fusion directory version 1.3 on debian 9, but I can't install the Zimbra plugin with an error message

```
root@fd:~# apt-get install fusiondirectory-plugin-zimbra
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package fusiondirectory-plugin-zimbra
root@fd:~# apt-get install fusiondirectory-plugin-zimbra-schema
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package fusiondirectory-plugin-zimbra-schema
root@fd:~#
```

**Comment by bilbo-the-hobbit** [comment]
@s33k3rs 

The zimbra plugin doesn't exist in 1.3, i will only be available in 1.4

I you want to preview the zimbra plugin before is official release you can buy a subscription https://www.fusiondirectory.org/en/our-support-offers/

Cheers
