### ISSUE TITLE
Webservice documentation

### ISSUE THREAD

**Issue by b4cktr4ck5r3** [fusiondirectory/fusiondirectory#63]
Hello,

I search for a documentation of FusionDirectory's Webservice.

Do you have any link for me ?

Thanks !

**Comment by bilbo-the-hobbit** [comment]
Hello @b4cktr4ck5r3 

for FusionDirectory 1.3 its here https://stable-api.fusiondirectory.info/classfdRPCService.html#details

for FusionDirectory 1.4 its here https://rest-api.fusiondirectory.info/

Cheers
