### ISSUE TITLE
Fatal error: Uncaught Exception: Serialization of 'XMLParser' is not allowed with PHP 8

### ISSUE THREAD

**Issue by AlphaJack** [fusiondirectory/fusiondirectory#68]
**Describe the bug**
I'm getting the following errors when I click Next on the LDAP Setup wizard page

```
Error 	
Fatal Error
Uncaught TypeError: Unsupported operand types: int & string

Fatal error: Uncaught Exception: Serialization of 'XMLParser' is not allowed in [no active file]:0 Stack trace: #0 {main} thrown in [no active file] on line 0
```

From Nginx error log:

```
2021/09/17 14:53:15 [error] 19718#19718: *28998 FastCGI sent in stderr: "PHP message: PHP Fatal error:Uncaught Exception: Serialization of 'XMLParser' is not allowed in [no active file]:0 Stack trace:
#0 {main}
  thrown in [no active file] on line 0" while reading upstream, client: 1.2.3.4, server: example.org, request: "GET /fusiondirectory/setup.php HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "example.org"
```

**To Reproduce**
1. Set up Arch Linux, OpenLDAP 2.4.59, PHP 8.0.10 and FusionDirectory 1.4-dev
2. Import FusionDirectory required schemas with the Perl tool
3. Follow the Wizard until you need to configure LDAP, click Next

**Expected behavior**
The web installation wizard appears as with PHP 7

**Comment by bilbo-the-hobbit** [comment]
hello @AlphaJack 

Arch is not officially supported and PHP 8 is not supported.

To find our matrix of supported Distribution look here https://www.fusiondirectory.org/en/certified-distributions/

**Comment by AlphaJack** [comment]
It's not about Arch Linux, it's about a PHP error that in v7 is a warning and in v8 makes the webapp unusable.  
Any milestone for PHP 8 support?
