### ISSUE TITLE
Hardcoded running as root requirement in ldap-schema-manager

### ISSUE THREAD

**Issue by pboguslawski** [fusiondirectory/fusiondirectory#69]
There is [hardcoded running as root requirement](https://github.com/fusiondirectory/schema2ldif/blob/1.3-fixes/bin/ldap-schema-manager#L128) in ldap-schema-manager. This disallows one to use it for schema management of rootless slapd (i.e. when slapd is configured in container to run under gid/uid!=0 but with appropriate cn=config permissions set for this gid/uid during slapd initialization).

Consider removing this hardcoded requirement.

**Comment by bilbo-the-hobbit** [comment]
hello @pboguslawski 

our tools are currently rewritten in php for Fusiondirectory 1.4 so this will no longer the case in future version, 1.3.x is in maintenance mode only

Cheers
