### ISSUE TITLE
Checking sn and givenName when processing template with autogenerated id and dn is uid

### ISSUE THREAD

**Issue by thomascramer** [fusiondirectory/fusiondirectory#7]
When using templates and you have the DN to use "uid" and auto-generated id's; when you create a user with the same name as someone else you get a "There is already an entry with this 'Name' attribute in the system!".  

The issue looks like plugins/admin/users/class_userManagement.inc in the templateContinue() method on line 578, it does:

      $ldap->search ("(&(sn=".normalizeLdap($this->sn).")(givenName=".normalizeLdap($this->givenName)."))", array("givenName"));
      if ($ldap->count () != 0) {
        msg_dialog::displayChecks(array(msgPool::duplicated(_("Name"))));
      } else {

This makes sense if you were doing the primary DN was based on cn and there was and no cn generation going on.

I'm not sure the best fix for this, but when the dn is based on a uid, I should be able to support people with same name.

**Comment by bilbo-the-hobbit** [comment]
hello,

This code as been heavily rewritten to be more flexible and as gottne lots of fixes on 1.0.9.1.

Could you test a recent release

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

any new about this, if not i will close this bug

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

no more info closing the bug

Cheers
