### ISSUE TITLE
XML error in fusiondirectory.conf: Not well-formed (invalid token)

### ISSUE THREAD

**Issue by IT-Anthony** [fusiondirectory/fusiondirectory#70]
**Describe the bug**
En suivant l'installation détaillée dans le manuel utilisateur, à la toute fin de l'installation via la WebUI, j'obtiens une erreur de type "XML error in fusiondirectory.conf: Not well-formed (invalid token) at line 1". Pourtant, les permissions et autre sont normalement bonnes car j'ai lancé l'utilitaire "fusiondirectory-setup --check-config". Le token semble bien copié/collé, il s'agit d'une suite de nombres ou chiffres, avec un espace en début de fichier. J'ai essayé en supprimant cet espace mais rien n'y fait.

**To Reproduce**
Suivre la procédure
Finaliser l'installation via la WebUI
Copier le token, le coller dans le fichier /etc/fusiondirectory/fusiondirectory.conf
Mettre les permissions adéquates, ou utiliser l'utilitaire fusiondirectory-setup --check-config en tant que root

**Expected behavior**
L'installation est normalement terminée.

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - PHP: [ php 7.3 ]
 - PHP provenance: [original Debian] 
 - Browser [Brave, Vivaldi]

**Comment by bilbo-the-hobbit** [comment]
hello @IT-Anthony 

for help when installing FusionDirectory, please use the mailing list 

Cheers
