### ISSUE TITLE
LDAP groups with spaces

### ISSUE THREAD

**Issue by skeljuve** [fusiondirectory/fusiondirectory#71]
Hi.
With a new version 1.3 I can't edit "Roles membership" for user when I add/remove a role with spaces which exists in my LDAP. On previous version 1.0.14 I was able to do this. I receive an error "The field 'Name' contains invalid characters. ' ' is not allowed:"
Can you hint me, where I can modify to pass spaces check with roles? I don't want to include this to newer version, it's only for my own purpose.
Thanks.

PS. I create a new roles without spaces, but I can't rename old roles due to external links with other projects.

**Comment by coudot** [comment]
Hello,

try to uncheck "strict naming policy" in configuration, see https://fusiondirectory-user-manual.readthedocs.io/en/1.3/fusiondirectory/configuration/configuration.html#people-and-group-storage

**Comment by skeljuve** [comment]
Thank for quickly answer.
It's already unchecked, so, "strict naming policy" doesn't influence. May be this is a bug or this parameter doesn't influence to Roles.

**Comment by coudot** [comment]
In this case this is hardcoded, you must patch the code.

**Comment by skeljuve** [comment]
Could you hint me, which files/functions this related?

**Comment by coudot** [comment]
Edit this line: https://github.com/fusiondirectory/fusiondirectory/blob/1.3-fixes/plugins/admin/groups/class_ogroup.inc#L217

For example:
```
          new StringAttribute(
            _('Name'), _('Name of this group'),
            'cn', TRUE,
            '', '', (strict_uid_mode() ? '/^[a-z0-9_-]+$/' : '/^[a-z0-9_.-\s]+$/i')
          ),
```

**Comment by bilbo-the-hobbit** [comment]
hello @skeljuve 

note that the correct method to report a bug is to follow the guidelines here : https://github.com/fusiondirectory/fusiondirectory/blob/8fbbc40114b6d0de4302cd353104342135d01cab/CONTRIBUTING.md 

Cheers

**Comment by skeljuve** [comment]
Thanks a lot @coudot 
A have changed to this:
`(strict_uid_mode() ? '/^[a-z0-9_-]+$/i' : '/^[-a-z0-9_.\s]+$/i')`
and now it works

**Comment by coudot** [comment]
@skeljuve Benoit is right, you should report this issue/feature request to the project, following contribution guidelines
