### ISSUE TITLE
LDAP connection without base suffix

### ISSUE THREAD

**Issue by lpellissier** [fusiondirectory/fusiondirectory#77]
Hi,

**Describe the bug**
I can't setup FusionDirectory to connect to 389 Directory Server. 
Connection with the CLI works this way :
`$ ldapsearch -H ldap:/ldap.me.fr:389 -D "cn=Directory Manager" -b "dc=me,dc=fr" -W -x uid=toto`

Our bind DN is `cn=Directory Manager` without any suffix, but FusionDirectrory needs to add one from the `Base` field of the LDAP `setup.php` form. Where `Base` field is required and can't be left empty.

**To Reproduce**
1. Go to '`/setup.php`'
2. Click on LDAP configuration tab
3. Error : `User connection 'cn=Directory Manager,dc=me,dc=fr' failed !`

**Expected behavior**
I need to connect FusionDirectory to the LDAP server just with credential : `cn=Directory Manager` without any bind suffix added.

**Desktop (please complete the following information):**
 - OS: CentOS 7.9
 - PHP: 7.3.33
 - PHP provenance: remi
 - Browser Firefox
 - Version 108

**Comment by bilbo-the-hobbit** [comment]
Hello @lpellissier 

Please excuse the long delay, but we don't support 389DS anymore and centos 7 is on the way out

Cheers
