### ISSUE TITLE
fusiondirectory-plugins-manager script does not install plugins

### ISSUE THREAD

**Issue by Window-Hero** [fusiondirectory/fusiondirectory#78]
After manually installing all apparently relevant components, the fusiondirectory-plugins-manager script will run without errors, will properly detect plugins in a directory when offered, will register those plugins seemingly correctly in the plugin manager on the configured ldap server, but will not apparently move any files to the fusion directory install (I used a custom directory, not sure if that matters, but it's not putting them in the default directory instead), so obviously the plugin does not function.

**To Reproduce**
1. Download the helper scripts from the fusiondirectory-tools repo (I considered posting this issue there, and will if requested, but there is no issue history or template there, so I suspected issues may be consolidated here).  This is an involved and somewhat touchy process that required a lot of files in very specific locations and a few odd php components.
2. Clone the fusiondirectory-plugins repo
3. fusiondirectory-plugins-manager --set-var fd_home=/path/to/fusiondirectory/ --install-plugin /path/to/plugin/repo/
4. Select whatever plugins you want, I'm trying to add public-forms, invitations, and posix
5. fusiondirectory-configuration-manager --set-var fd_home=/path/to/fusiondirectory/ --update-cache --update-locales

**Expected behavior**
The plugins would be installed and ready for configuration through the web panel.

**Desktop (please complete the following information):**
 - OS: Debian
 - PHP:  php 7.4
 - PHP provenance: Debian apt repo 
 - Browser: Tried on Firefox and Chrome, not that that's relevant

**Comment by tdockx** [comment]
Hello @Window-Hero, 

Could you please confirm that you are trying to install plugins released by FusionDirectory and not third parties ?
I am saying this because all our plugins are tagged with [Package] within their description.yaml. 

Currently, any tagged plugin "package" should be installed from the official repository. 
During registration of the "official" plugins, no files will be moved within your FD installation, as they should be installed/moved via your distribution package manager directly.

Hope it makes sense.

Kind regards,
Thibault.

**Comment by Window-Hero** [comment]
Yes I am trying to install first party plugins, and I did find the packaged tag some time later in the night and was able to get the plugins to install by commenting out that check in the script.  I was going to post about this later today.  Unfortunately my distribution package manager includes version 1.3, which does not include and is incompatible with the invitations plugin, which is very important to my use case.

I would imagine the reason the script has that line in it is because it gets called by some package managers, and in that case the script should only handle registration within LDAP.  What I would recommend is that the descriptions of plugins on GitHub should not include this tag (since they *aren't* packaged in that state), and that this tag should instead be added during your build process.

**Comment by bilbo-the-hobbit** [comment]
Hello @Window-Hero 

Wich distribution are you using ? Yes fusiondirectory-plugin-manager only work with plugin written for 1.4 specifically

as said by @tdockx the system is only mean to be used with external plugin, as we provide packaged version for every release we release publicly

Cheers
