### ISSUE TITLE
"Actions" drop-down doesn't work with HTTPS

### ISSUE THREAD

**Issue by iamrekcah** [fusiondirectory/fusiondirectory#8]
After logging in and navigating to [Users] or [Groups], hovering over [Actions] should release a drop-down menu, from which I can create a new new [User/Group/etc]. Under some cases, that hovering over [Actions] does **not** release the drop-down menu (see image below).

| Platform     | Browser                           | HTTPS | Dropdown Menu shows |
| -------------- | ------------------------------- | :-------: | :-----------------------------: |
| Windows 7 | Chrome 39.0.2171.95 m | No        | Success                         |
| Windows 7 | Chrome 39.0.2171.95 m | Yes      | Fail                                 |
| Windows 7 | Firefox 34.0.5                  | No       | Fail                                 |
| Windows 7 | Firefox 34.0.5                  | Yes      | Fail                                |

![2014-12-30 20_12_57-fusiondirectory](https://cloud.githubusercontent.com/assets/1663284/5584898/a77b3d5a-9060-11e4-8524-cf24ed46e98f.png)

I don't think this is relevant, but my setup is using Lighttpd 1.4.31-4.

**Comment by MCMic** [comment]
Which FD version are you using?
Can you look into javascript error console in Firefox and see what shows up?
Can you create an account on https://forge.fusiondirectory.org/ and open a bug there?

**Comment by bilbo-the-hobbit** [comment]
hello,

lots of code changed til you entered this bug. can you still reproduce this bug with the 1.0.9.1 release

Cheers

**Comment by iamrekcah** [comment]
I don't have FusionDirectory installed anymore. Sorry.

**Comment by bilbo-the-hobbit** [comment]
hello,

thank you for the answer, closing it

Cheers
