### ISSUE TITLE
Fusiondirectory 1.4 need = PHP 7.4

### ISSUE THREAD

**Issue by Trylam** [fusiondirectory/fusiondirectory#81]
I see in the [documentation](https://fusiondirectory-developer-documentation.readthedocs.io/en/1.4/fusiondirectory/distribution/certified-distribution.html) that fusiondirectory need php 7.4, when will fusiondirectory move to php8?

**Comment by tdockx** [comment]
Hi Trylan, 

It is on our roadmap, we've had some request to contribute to it, but no codes have been shared yet.
Would you like to contribute towards it, you are more than welcomed as well.

Although on our roadmap, we have no definitive date yet. 
We've made some attempts already, but there is lots of work remaining. 

Thanks,

Thibault.

**Comment by Window-Hero** [comment]
It should probably be specified in the package that this older version of PHP is needed, because as it stands the dependency doesn't specify, so the newest available version (in my case 8.2) will be installed by default.

**Comment by Window-Hero** [comment]
It may also be worth updating the documentation to include guidance for adding an alternate repo for old version of PHP, since many mainstream repos are dropping it.

**Comment by tdockx** [comment]
I'll discuss this internally, as we follow a quite strict and defined distribution support, information is available in the official documentation.

**Comment by loicsikidi** [comment]
Hi,

I take the liberty to reopen the subject knowing that 2024 will [sound the death knell](https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/) of Centos 7/8.

Do you plan to share a roadmap about the support of _php8_?

If it not the case, from my understanding **fusiondirectory** is an atomic project:

- [core](https://github.com/fusiondirectory/fusiondirectory)
- [fusiondirectory-tools](https://github.com/fusiondirectory/fusiondirectory-tools)
- [fusiondirectory-plugins](https://github.com/fusiondirectory/fusiondirectory-plugins)
- [fusiondirectory-integrator](https://github.com/fusiondirectory/fusiondirectory-integrator)

In the scenario, where the work was done by the community:

1. what would be the order of priority (by project)
2. does each project have sufficient unit or integration test coverage to validate non-regression?

Thank you in advance for your answer :rocket:.

KR,
