### ISSUE TITLE
source package Debian fusiondirectory v1.4 bullseye

### ISSUE THREAD

**Issue by Trylam** [fusiondirectory/fusiondirectory#82]
Hello, 
fusiondirectory version 1.4 is available for bullseye but it's impossible to find the sources. Are the package sources available? (I'm not talking about the source code but the package sources.) If yes, could you give me the link, if not, why is it not made available?

**Comment by bilbo-the-hobbit** [comment]
Hello @Trylam 

We don't publish the sources for the packages. FusionDirectory is free software, the packaging is not.

Cheers
