### ISSUE TITLE
Automatic account expiration and notification

### ISSUE THREAD

**Issue by eickeh** [fusiondirectory/fusiondirectory#84]
We're running FusionDirectory 1.4.0 and search for a mechanism to automatically disable an account on a given date (preferrably the "End date" provided by the personal plugin). Additionally, a configurable amount of time in advance, the user and his/her manager should get notified about the upcoming expiry. Also, at least for the start, it would be nice if I (the admin) could be notified about an upcoming expiry or the expiry itself. 
As our users hardly use and login into FusionDirectory directly, we can't use a trigger on anything done in the user interface.

Is something like that possible out of the box? My only alternative would be to read out LDAP by a script and implement the functionality there.

**Comment by sideeffect42** [comment]
Yes, this would be a very practical feature, indeed.

**Comment by bilbo-the-hobbit** [comment]
hello,

FusionDirectory has those functionalities you can look at user-reminder and the concept of the supann ressource. The rest is implementation details and is, of course, not detailed into the manual

Cheers

**Comment by eickeh** [comment]
Thanks for the pointers! On a first glimpse, this looked good. I'll (hopefully) post some instructions here once we got it doing what we want.

**Comment by sideeffect42** [comment]
@bilbo-the-hobbit Thank you for the pointer to the user-reminder plugin. I just had a look at it and it seems that its functionality is very limited.

It would be nice if the action extension functionality could be disabled and the recipients of the alerts could be configured.
In my case e.g. I don't want users to be notified about their expiring account, only the admin should be notified so they can take the necessary actions.

**Comment by bilbo-the-hobbit** [comment]
hello @sideeffect42 

In Fusiondirectory 1.5 you will be able to use Orchestrator and Supann LifeCycle to manage all the life cycle of account. 

https://fusiondirectory-user-manual.readthedocs.io/en/1.4/fusiondirectory-orchestrator/index.html

This will be much more flexible than old user reminder

So i'am closing this
