### ISSUE TITLE
Repository signature key 0xFE0FEAE5AC483A86 expired on April 19th

### ISSUE THREAD

**Issue by eickeh** [fusiondirectory/fusiondirectory#86]
**Describe the bug**
APT update fails because the fusiondirectory signature key expired again:
```
W: Failed to fetch https://public.fusiondirectory.org/debian/fusiondirectory-integrator/dists/bullseye/InRelease  The following signatures were invalid: EXPKEYSIG FE0FEAE5AC483A86 FusionDirectory Packages Signing Key <contact@fusiondirectory.org>

$> gpg -v /usr/share/keyrings/FD-archive-key
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: Note: signature key FE0FEAE5AC483A86 expired Fri 19 Apr 2024 10:44:58 AM CEST
pub   rsa4096 2019-07-30 [SC] [expired: 2024-04-19]
      C3A287F0C5805909519632E7FE0FEAE5AC483A86
uid           FusionDirectory Packages Signing Key <contact@fusiondirectory.org>
sig        FE0FEAE5AC483A86 2021-04-20   [selfsig]
sub   rsa4096 2019-07-30 [E] [expired: 2024-04-19]
sig        FE0FEAE5AC483A86 2021-04-20   [keybind]
```

**To Reproduce**
1. Install fusiondirectory apt repo
2. perform apt update

**Expected behavior**
Repo is signed with valid key and apt updates runs without error :D

**Comment by tdockx** [comment]
Hello @eickeh,

You should update your reference key with the updated one.

Here the related doc : https://fusiondirectory-user-manual.readthedocs.io/en/1.4/gpg/gpg-keys.html

Let us know if ok.

Regards,
Thibault

**Comment by eickeh** [comment]
Hi @tdockx,

Thanks for your reply. However, the key I mentioned is already the latest one (compare the key IDs), but it expired about three weeks ago :D

**Comment by tdockx** [comment]
Hello @eickeh,

This is very strange, we indeed had an expiry of key, but we could re-update properly after the key update.
I'll inquire the team and see what's happening to you.

Let you know.
Thibault.

**Comment by eickeh** [comment]
Hello,

Thanks! After downloading the key again, it does work again :tada: 
Is it intended that it's only valid for one year (expires: 2025-04-19)?

**Comment by popindavibe** [comment]
Just to comment since I had a similar issue, only the key available on HTTPS directly from https://public.fusiondirectory.org/FD-archive-key works for me too. 
Downloading from keys.openpgp.org I get a key that fails verification.

**Comment by bilbo-the-hobbit** [comment]
@eickeh yes our keys are valid only for one year and updated each year

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello @popindavibe 

for @eickeh it worked after a renewed the subkey are you sure you redownloaded the whole key set if you had a previous one

Cheers
